# 使用官方的Java镜像作为基础镜像
FROM openjdk:8-jdk-alpine

# 设置工作目录
WORKDIR E:/DockerData/java

# 复制构建文件到容器中
COPY target/medical-media.jar medical-media.jar

# 安装Nginx
RUN apk update && apk add nginx

# 复制Nginx配置文件
COPY nginx.conf /etc/nginx/nginx.conf

COPY D:/Develop/nginx-1.22.1/webapp/medical /webapp
# 暴露Nginx的端口
EXPOSE 83



# 容器启动时执行的命令
CMD ["nginx", "-g", "daemon off;"]
# 设置容器启动命令
CMD ["java", "-jar", "app.jar"]
